# - name: "Copy {{component}} service"
#   ansible.builtin.copy:
#     src: "{{component}}.service"
#     dest: "/etc/systemd/system/{{component}}.service"

- name: Copy catalogue service
  ansible.builtin.template:
    src: catalogue.service
    dest: "/etc/systemd/system/catalogue.service

- name: deamon realod and start
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start and enable catalogue
  ansible.builtin.service:
    name: catalogue
    state: restarted
    enabled: yes
    
